In [14]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect("logs.db")

# Load logs into a pandas DataFrame
df = pd.read_sql_query("SELECT * FROM request_logs ORDER BY timestamp DESC", conn)

df

,id,timestamp,headers,path,method,status_code,response_body,client_name
0,7,2025-04-30 00:52:07.796565,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/score/single,POST,200,"{""make"":""Toyota"",""model"":""Camry"",""year"":2029,""...",ClientA
1,6,2025-04-30 00:45:06.570524,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/score/single,POST,200,"{""make"":""Toyota"",""model"":""Camry"",""year"":2020,""...",ClientA
2,5,2025-04-30 00:38:33.641159,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/score/single,POST,200,"{""make"":""Toyota"",""model"":""Camry"",""year"":2020,""...",ClientA
3,4,2025-04-30 00:37:58.076039,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/openapi.json,GET,200,"{""openapi"":""3.1.0"",""info"":{""title"":""Vehicle Sc...",None
4,3,2025-04-30 00:37:57.766255,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/docs,GET,200,\n <!DOCTYPE html>\n <html>\n <head>\...,None
5,2,2025-04-30 00:37:52.501685,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/,GET,200,"{""status"":""ok""}",None
6,1,2025-04-30 00:35:08.104627,"{""host"": ""127.0.0.1:8000"", ""connection"": ""keep...",/,GET,200,"{""status"":""ok""}",None

In [17]:
df1 = df[df['id']==7]['response_body']

print(df1.iloc[0])

{"make":"Toyota","model":"Camry","year":2029,"mileage":50000.0,"engine_size":2.5,"score":750.25}